### model
model_name_or_path: /mnt/petrelfs/share_data/zengxiangyu/models/Qwen2.5-VL-7B-Instruct
image_max_pixels: 262144
video_max_pixels: 602112 # useless
video_min_pixels: 100352 # useless
video_maxlen: 768
max_token_number: 16384
min_token_number: 1024
trust_remote_code: true
flash_attn: fa2 
# use_fast_tokenizer: false

### method
stage: sft
do_train: false
finetuning_type: lora
lora_rank: 8
lora_target: all

### dataset
### dataset
dataset: llava_video_caption_youtube_2_3_m_qwen3vl_rewritten_21386_converted
template: qwen2_vl
cutoff_len: 40000
overwrite_cache: false
preprocessing_batch_size: 128
preprocessing_num_workers: 16
dataloader_num_workers: 16
tokenized_path: saves/llava_video_caption_youtube_2_3_m_qwen3vl_rewritten_21386_converted/dataset/sft
accelerator_config:
  dispatch_batches: false


### output
output_dir: /mnt/petrelfs/zhangzhiqiu/LLaMA-Factory/saves/videochat-o3-sft-temp/ckpt
overwrite_output_dir: true

# # ### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-5
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
# resume_from_checkpoint: null

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
